services:
  functions:
      environment:
        NOTEBOOK_CHAT_URL: "${NOTEBOOK_CHAT_URL}"
        NOTEBOOK_GENERATION_URL: "${NOTEBOOK_GENERATION_URL}"
        AUDIO_GENERATION_WEBHOOK_URL: "${AUDIO_GENERATION_WEBHOOK_URL}"
        DOCUMENT_PROCESSING_WEBHOOK_URL: "${DOCUMENT_PROCESSING_WEBHOOK_URL}"
        ADDITIONAL_SOURCES_WEBHOOK_URL: "${ADDITIONAL_SOURCES_WEBHOOK_URL}"
        NOTEBOOK_GENERATION_AUTH: "${NOTEBOOK_GENERATION_AUTH}"
        